version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.18
            bundle install
            bundle exec rake
